name: flutterdex
description: A Pokédex made with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  http: ^0.13.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
